AMALLAR = [
    "11 marta salovat ayting: 'Allohumma solli ‘ala Muhammad va ‘ala āli Muhammad'.",
    "Bugun ota-onangizni holidan xabar oling yoki ular uchun duo qiling.",
    "Ovqatdan oldin 'Bismillah', keyin esa 'Alhamdulillah' deb shukr qiling.",
    "Bugun kamida bitta kishiga samimiy tabassum bilan muomala qiling.",
    "33 marta 'Subhanalloh' deb ayting.",
    "33 marta 'Alhamdulillah' deb ayting.",
    "33 marta 'Allohu Akbar' deb ayting.",
    "Bugun 11 marta 'Astag‘firullohal aziym' deb istig‘for ayting.",
    "Bugun ko‘chada yoki ish joyida ko‘rgan chiqindini olib tashlang.",
    "Bugun berilgan ne’matlar uchun kechqurun shukr qiling.",

    "11 marta 'La ilaha illalloh' deb ayting.",
    "Bugun biron kishining ko‘nglini og‘ritmaslikka e’tibor bering.",
    "11 marta 'Hasbiyallohu la ilaha illa Huva' deb ayting.",
    "Bugun ota-onangizni xursand qiladigan kichik ish qiling.",
    "Imkoni bo'lsa bugun har bir kishiga muloyim va past ovozda javob bering.",
    "11 marta 'Subhanallohi va bihamdihi' deb ayting.",
    "Bugun biror yaxshilikni yashirincha qilishga harakat qiling.",
    "Bugun g‘azab kelganda sukut saqlashni tanlang.",
    "Bugun yolg‘on, g‘iybat va behuda gapdan saqlaning.",
    "Bugun bir kishiga yaxshi niyat qiling.",

    "11 marta 'Robbighfir liy' deb duo qiling.",
    "Bugun sizga ozor bergan kishini ichingizdan kechiring.",
    "Bugun har bir ishni shoshmasdan, sokin bajaring.",
    "Bugun ko‘zingizni haromdan saqlashga e’tibor qarating.",
    "11 marta salovat ayting: 'Allohumma solli ‘ala Muhammad'.",
    "Bugun bir kishining gapini bo‘lmasdan oxirigacha tinglang.",
    "Bugun o‘zingiz uchun emas, boshqalar uchun duo qiling.",
    "Bugun berilgan ne’matlarni isrof qilmaslikka harakat qiling.",
    "Bugun birovni masxara qilmaslikka qat’iy niyat qiling.",
    "Bugun qalbingizni hasaddan poklashga urinib ko‘ring.",

    "33 marta 'Astag‘firulloh' deb ayting.",
    "Bugun kamida bitta kishiga yaxshi so‘z ayting.",
    "Bugun sabrni tanlab, jahlni yuting.",
    "Bugun qilayotgan ishni ixlos bilan bajarishga harakat qiling.",
    "11 marta 'Ya Hayyu Ya Qayyum' deb ayting.",
    "Bugun birovning xatosini fosh qilmasdan yopishga urinib ko‘ring.",
    "Bugun o‘zingizni boshqalardan ustun qo‘ymaslikka harakat qiling.",
    "Bugun bir daqiqa sukutda Allohni yodga oling.",
    "Bugun tilingizni behuda gapdan tiyib turing.",
    "Bugun sabr bilan sinovga qarshi turing.",

    "11 marta 'Alhamdulillahi ‘ala kulli hal' deb ayting.",
    "Bugun ota-onangiz yoki ustozingiz uchun duo qiling.",
    "Bugun birovning haqqini yemaslikka alohida e’tibor bering.",
    "Bugun oz bo‘lsa ham sadaqa qilishni niyat qiling.",
    "11 marta 'Subhanakallohumma va bihamdika' deb ayting.",
    "Bugun birovga ozor bermasdan kunni yakunlashga harakat qiling.",
    "Bugun qalbingizda tavozelikni kuchaytiring.",
    "Bugun yaxshi gumonda bo‘lishni tanlang.",
    "Bugun biror gunohga yaqinlashsangiz, undan chekining.",
    "Bugun qilgan amallaringizni kechqurun o‘zingizcha hisob qiling.",

    "11 marta 'Allohumma innaka ‘afuvvun tuhibbul ‘afva fa‘fu ‘anni' deb ayting.",
    "Bugun kichik bo‘lsa ham foydali ish qiling.",
    "Bugun sukutni afzal ko‘rish orqali xatodan saqlaning.",
    "Bugun tilingizdan chiqqan so‘zlarga mas’ul bo‘ling.",
    "11 marta 'La havla va la quvvata illa billah' deb ayting.",
    "Birovni ranjitgan bo‘lsangiz, undan bugun uzr so‘rang.",
    "Alloh sizni ko‘rib turganini eslab yuring.",
    "Bugun sabr va shukrni birga tutishga harakat qiling.",
    "Bugun qalbingizni pok niyat bilan to‘ldiring.",
    "Bugun oxiratni eslab, dunyoga berilib ketmaslikka urinib ko‘ring.",

    "Botdagi 'Tasodfiy oyat' funksiyasini ishlatib, 3 ta oyat o'qing.",
    "Botdagi 'Tasodifiy hadis' funksiyasini ishlatib, 3 ta yangi hadis o'qing."
    
    
    "Bugun uydan chiqishda 'Bismillahi tavakkaltu 'alalloh' deb niyat qiling.",
    "Bugun bitta shirinlik yoki meva bilan biror kishini iftorlikda xursand qiling.",
    "11 marta: 'Subhanallohi val hamdu lillahi va la ilaha illallohu vallohu akbar' deb ayting.",
    "Bugun ijtimoiy tarmoqlarda ma'nosiz va bemaza kontetlardan saqlaning, YouTube da mazmunli foydali video ko'rib uni yaqinlarga ham ulashing.",
    "Bugun biror kishini og'irini yengil qiling.",
    "Bugun ovqatlanishda faqat o'ng qo'l bilan va o'z oldingizdan yeyishga qat'iy amal qiling.",
    "11 marta: 'Allohumma inni as'alukal jannah' deb duo qiling.",
    "Bugun uydagi biron bir buzilgan yoki tartibsiz narsani tuzatib qo'ying.",
    "Bugun farzandlaringizga yoki kichiklarga birgina yaxshi xulqni o'rgating.",
    "11 marta: 'Robbana atina fid-dunya hasanatan va fil axiroti hasanah' deb ayting.",

    "Bugun ko'chada hayvonlarga suv yoki yegulik bering.",
    "Bugun biron tanishingizga 'Sizni Alloh yo'lida yaxshi ko'raman' deb ayting.",
    "11 marta: 'Subhanallohil 'azim va bihamdihi' deb ayting.",
    "Bugun kiyimingiz yoki poyabzalingizni ozoda tutishga alohida e'tibor bering.",
    "Bugun iftor vaqtida suv ichishdan oldin chin dildan duo qiling.",
    "Bugun biror kishining aybini ko'rsangiz, uni o'ziga tushuntiring va uni boshqalardan sir tuting.",
    "11 marta: 'Allohumma a'inni 'ala zikrika va shukrika va husni 'ibadatik' deb ayting.",
    "Bugun ishxonada yoki o'qishda o'z vazifangizni eng namunali darajada bajaring.",
    "Bugun ko'p gapirishdan ko'ra, ko'proq tinglashga harakat qiling.",
    "11 marta: 'Ya Zal Jalali val Ikrom' deb Allohga nido qiling.",

    "Bugun biror kishining yaxshi amalini boshqalar oldida maqtab, ko'nglini ko'taring.",
    "Bugun qo'shningizga yoki yaqin do'stingizga kutilmagan kichik sovg'a bering.",
    "11 marta: 'La ilaha illa anta subhanaka inni kuntu minaz-zolimin' deb ayting.",
    "Bugun ginangiz bor kishi bilan salom-alikni tiklang.",
    "Bugun o'z xatolaringizni o'ylab, ularni takrorlamaslikka niyat qiling.",
    "11 marta: 'Allohumma barik lana fi Ramazan' deb duo qiling.",
    "Bugun iftorlikdan so'ng 5 daqiqa dunyo ishlaridan uzilib, tafakkur qiling.",
    "Bugun 'Al-Fotiha' surasining ma'nosini o'qib, tushunishga harakat qiling.",
    "Bugun qilgan xatolar va gunohlaringiz uchun chin dildan tavba qiling."
]




